"""
core/chatgpt_bridge.py — ORACLE ChatGPT Bridge

Doctrine:
  ORACLE may draft to ChatGPT.
  ORACLE may not submit to ChatGPT without Noah approval.

Purpose:
  Allow ORACLE to prepare and transfer structured questions/messages to the
  ChatGPT desktop app (or browser tab) on Noah's second screen.

Core rules:
  - Never sends without explicit Noah approval (APPROVE_SEND_CHATGPT)
  - Never uses blind pixel coordinates — semantic window detection first
  - Never sends secrets, API keys, passwords, raw memory dumps
  - Fails cleanly if ChatGPT window is not found
  - Compresses context before sending; preserves source boundaries

Usage:
  python core/chatgpt_bridge.py --smoke
  python core/chatgpt_bridge.py --dry-run --message "What is X?"
  python core/chatgpt_bridge.py --status
"""

import json
import sys
import uuid
import re
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

if getattr(sys, "frozen", False):
    ROOT = Path(sys.executable).parent
else:
    ROOT = Path(__file__).parent.parent

sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "core"))

BRIDGE_LOG_FILE = ROOT / "Memory" / "chatgpt_bridge_log.json"
MAX_LOG_ENTRIES = 200

# ── ChatGPT window detection ───────────────────────────────────────────────────
CHATGPT_TITLE_FRAGMENTS = [
    "chatgpt", "chat.openai.com", "openai", "chatgpt - google chrome",
    "chatgpt - microsoft edge", "chatgpt - brave",
]
CHATGPT_PROCESS_NAMES = {
    "chatgpt.exe",     # desktop app
    "chrome.exe",      # browser fallback
    "msedge.exe",
    "brave.exe",
    "firefox.exe",
}

# ── Secret patterns to redact before any bridge send ──────────────────────────
SECRET_PATTERNS = [
    (r"sk-[A-Za-z0-9\-_]{8,}", "[REDACTED_API_KEY]"),
    (r"(?i)(password|passwd|pwd)\s*[:=]\s*\S+", "[REDACTED_PASSWORD]"),
    (r"\b\d{3}-\d{2}-\d{4}\b", "[REDACTED_SSN]"),
    (r"\b(?:\d{4}[- ]?){3}\d{4}\b", "[REDACTED_CARD]"),  # credit card
    (r"(?i)api[_-]?key\s*[:=]\s*\S+", "[REDACTED_API_KEY]"),
    (r"(?i)secret\s*[:=]\s*\S+", "[REDACTED_SECRET]"),
    (r"(?i)token\s*[:=]\s*[A-Za-z0-9\-_\.]{10,}", "[REDACTED_TOKEN]"),
]

MAX_MESSAGE_CHARS = 4000   # compress context if longer than this


# ── Bridge message envelope ───────────────────────────────────────────────────

@dataclass
class BridgeMessage:
    id: str = field(default_factory=lambda: uuid.uuid4().hex[:8])
    context: str = ""
    request: str = ""
    constraints: str = ""
    expected_output: str = ""
    approval_status: str = "DRAFT"   # DRAFT | APPROVED | SENT | BLOCKED
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    sent_at: str = ""
    target_window: str = ""
    dry_run: bool = True
    redactions_applied: int = 0

    def envelope(self) -> str:
        """Formatted envelope text that gets pasted into ChatGPT."""
        parts = [
            "ORACLE → ChatGPT BRIDGE MESSAGE",
            "─" * 40,
        ]
        if self.context:
            parts += ["Context:", self.context, ""]
        if self.request:
            parts += ["Request:", self.request, ""]
        if self.constraints:
            parts += ["Constraints:", self.constraints, ""]
        if self.expected_output:
            parts += ["Expected output:", self.expected_output, ""]
        parts += [
            "─" * 40,
            f"Approval status : {self.approval_status}",
            f"Message ID      : {self.id}",
            f"Generated by    : ORACLE.AI (governed draft)",
        ]
        return "\n".join(parts)

    def summary(self) -> str:
        env = self.envelope()
        return (
            f"\n  [BRIDGE MESSAGE {self.id}]\n"
            f"  Status  : {self.approval_status}\n"
            f"  Target  : {self.target_window or '(not set)'}\n"
            f"  Dry run : {self.dry_run}\n"
            f"  Redactions applied: {self.redactions_applied}\n"
            f"\n  ENVELOPE:\n"
            + "\n".join(f"    {line}" for line in env.split("\n"))
            + "\n"
        )


# ── ChatGPT Bridge ─────────────────────────────────────────────────────────────

class ChatGPTBridge:
    """
    Governs all communication from ORACLE to ChatGPT.

    Flow:
      1. draft_message()       — build envelope, redact secrets, compress
      2. find_chatgpt_window() — locate ChatGPT semantically
      3. insert_message()      — paste into input field (draft only by default)
      4. approve_send()        — Noah must call this; only then does Enter get pressed
    """

    def __init__(self):
        self._log: list = []
        self._pending: dict[str, BridgeMessage] = {}
        self.load_log()

    # ── Secret redaction ──────────────────────────────────────────────────────

    @staticmethod
    def redact_secrets(text: str) -> tuple[str, int]:
        """Return (cleaned_text, redaction_count)."""
        count = 0
        for pattern, replacement in SECRET_PATTERNS:
            new_text, n = re.subn(pattern, replacement, text)
            if n:
                text = new_text
                count += n
        return text, count

    @staticmethod
    def compress_context(text: str, max_chars: int = MAX_MESSAGE_CHARS) -> str:
        """Truncate and summarize if over limit."""
        if len(text) <= max_chars:
            return text
        half = max_chars // 2
        return (
            text[:half]
            + f"\n\n[... {len(text) - max_chars} characters compressed ...]\n\n"
            + text[-half:]
        )

    # ── Message drafting ──────────────────────────────────────────────────────

    def draft_message(
        self,
        request: str,
        context: str = "",
        constraints: str = "",
        expected_output: str = "",
        dry_run: bool = True,
    ) -> BridgeMessage:
        """Build a governed bridge message envelope. Does not send or paste."""
        # Redact secrets from all fields
        context_clean, r1 = self.redact_secrets(context)
        request_clean, r2 = self.redact_secrets(request)
        constraints_clean, r3 = self.redact_secrets(constraints)
        total_redactions = r1 + r2 + r3

        # Compress if needed
        context_clean = self.compress_context(context_clean)

        msg = BridgeMessage(
            context=context_clean,
            request=request_clean,
            constraints=constraints_clean or (
                "Do not act on any information from this message without Noah's direction. "
                "This is a governed query from ORACLE.AI."
            ),
            expected_output=expected_output,
            approval_status="DRAFT",
            dry_run=dry_run,
            redactions_applied=total_redactions,
        )
        self._pending[msg.id] = msg
        self._log_entry("draft", msg)
        return msg

    # ── Window detection ──────────────────────────────────────────────────────

    def find_chatgpt_window(self) -> Optional[dict]:
        """
        Search visible windows for ChatGPT.
        Returns dict with title, handle, method. Returns None if not found.
        Never moves the mouse to "check" coordinates.
        """
        candidates = []

        # Method 1: pygetwindow title scan
        try:
            import pygetwindow as gw
            for w in gw.getAllWindows():
                title_lower = w.title.lower()
                for frag in CHATGPT_TITLE_FRAGMENTS:
                    if frag in title_lower:
                        candidates.append({
                            "title": w.title,
                            "handle": getattr(w, "_hWnd", 0),
                            "method": "pygetwindow_title_match",
                            "match_fragment": frag,
                        })
                        break
        except Exception:
            pass

        # Method 2: pywinauto window search (preferred — semantic)
        if not candidates:
            try:
                from pywinauto import Desktop
                desk = Desktop(backend="uia")
                for win in desk.windows():
                    try:
                        title = win.window_text() or ""
                        proc = getattr(win, "process_id", lambda: 0)()
                        title_lower = title.lower()
                        for frag in CHATGPT_TITLE_FRAGMENTS:
                            if frag in title_lower:
                                candidates.append({
                                    "title": title,
                                    "handle": win.handle,
                                    "method": "pywinauto_uia_title_match",
                                    "match_fragment": frag,
                                })
                                break
                    except Exception:
                        pass
            except Exception:
                pass

        if not candidates:
            return None

        # Prefer desktop app over browser if both found
        desktop_app = next(
            (c for c in candidates if "chatgpt.exe" in c.get("title", "").lower()), None
        )
        return desktop_app or candidates[0]

    # ── Window focus ──────────────────────────────────────────────────────────

    def focus_chatgpt(self, window_info: dict) -> bool:
        """Focus the ChatGPT window. Returns True on success."""
        handle = window_info.get("handle", 0)
        title = window_info.get("title", "")

        # pywinauto preferred (semantic)
        try:
            from pywinauto import Desktop
            desk = Desktop(backend="uia")
            for win in desk.windows():
                try:
                    if win.handle == handle or win.window_text() == title:
                        win.set_focus()
                        return True
                except Exception:
                    pass
        except Exception:
            pass

        # pygetwindow fallback
        try:
            import pygetwindow as gw
            wins = gw.getWindowsWithTitle(title)
            if wins:
                wins[0].activate()
                return True
        except Exception:
            pass

        # WinAPI fallback
        if handle:
            try:
                import ctypes
                ctypes.windll.user32.SetForegroundWindow(handle)
                return True
            except Exception:
                pass

        return False

    # ── Input field targeting ─────────────────────────────────────────────────

    def find_input_field(self, window_info: dict) -> Optional[object]:
        """
        Use UIAutomation/pywinauto to find the ChatGPT text input field.
        Never relies on coordinates.
        Returns the control object if found, None otherwise.
        """
        try:
            from pywinauto import Desktop
            desk = Desktop(backend="uia")
            handle = window_info.get("handle", 0)
            title = window_info.get("title", "")

            target_win = None
            for win in desk.windows():
                try:
                    if win.handle == handle or win.window_text() == title:
                        target_win = win
                        break
                except Exception:
                    pass

            if not target_win:
                return None

            # Try to find the edit/input control
            for control_type in ("Edit", "Document", "TextInput"):
                try:
                    ctrl = target_win.child_window(control_type=control_type)
                    if ctrl.exists():
                        return ctrl
                except Exception:
                    pass

        except Exception:
            pass

        return None

    # ── Message insertion ─────────────────────────────────────────────────────

    def insert_message(
        self,
        msg: BridgeMessage,
        window_info: dict,
        dry_run: bool = True,
    ) -> tuple[bool, str]:
        """
        Paste the message envelope into ChatGPT's input field.
        DOES NOT press Enter — draft only unless approve_send() is called.
        Returns (success, detail).
        """
        msg.target_window = window_info.get("title", "?")

        if dry_run:
            return True, f"[DRY RUN] Would paste {len(msg.envelope())} chars into '{msg.target_window}'."

        if msg.approval_status == "BLOCKED":
            return False, "Message is BLOCKED — secrets detected or manually blocked."

        # Focus window
        if not self.focus_chatgpt(window_info):
            return False, f"Could not focus ChatGPT window: {msg.target_window}"

        # Find input field
        input_ctrl = self.find_input_field(window_info)

        envelope_text = msg.envelope()

        if input_ctrl:
            # Semantic injection — preferred
            try:
                import time
                input_ctrl.set_focus()
                time.sleep(0.3)
                input_ctrl.type_keys("^a", pause=0.1)    # select all
                input_ctrl.type_keys("{DELETE}", pause=0.1)
                # Use clipboard for longer text
                import pyperclip
                pyperclip.copy(envelope_text)
                input_ctrl.type_keys("^v", pause=0.1)
                return True, f"Message inserted via semantic UIAutomation into '{msg.target_window}'."
            except Exception as e:
                pass  # fall through to clipboard fallback

        # Clipboard fallback (focus must be on ChatGPT input field)
        try:
            import pyperclip
            import time
            pyperclip.copy(envelope_text)
            time.sleep(0.3)
            import pyautogui
            pyautogui.hotkey("ctrl", "v")
            return True, f"Message pasted via clipboard into '{msg.target_window}' (mouse fallback)."
        except Exception as e:
            return False, f"Could not insert message: {e}"

    # ── Approval gate ─────────────────────────────────────────────────────────

    def approve_send(self, message_id: str) -> tuple[bool, str]:
        """
        Noah calls this with APPROVE_SEND_CHATGPT to authorize pressing Enter.
        Only call after insert_message() has placed the text.
        """
        msg = self._pending.get(message_id)
        if not msg:
            return False, f"No pending message with ID '{message_id}'."
        if msg.approval_status == "BLOCKED":
            return False, "Message is BLOCKED and cannot be sent."

        msg.approval_status = "APPROVED"
        window_info = {}
        if msg.target_window:
            window_info = {"title": msg.target_window, "handle": 0}

        # Press Enter to send
        if not msg.dry_run:
            try:
                # Focus the window first
                if msg.target_window:
                    self.focus_chatgpt(window_info)

                import time
                time.sleep(0.3)

                # Try semantic press Enter on input control
                input_ctrl = self.find_input_field(window_info)
                if input_ctrl:
                    input_ctrl.type_keys("{ENTER}", pause=0.1)
                else:
                    import pyautogui
                    pyautogui.press("enter")

                msg.approval_status = "SENT"
                msg.sent_at = datetime.now(timezone.utc).isoformat()
                self._log_entry("sent", msg)
                self.save_log()
                return True, f"Message {message_id} sent to ChatGPT."
            except Exception as e:
                return False, f"Failed to send: {e}"
        else:
            msg.approval_status = "SENT"
            msg.sent_at = datetime.now(timezone.utc).isoformat()
            self._log_entry("sent_dry_run", msg)
            return True, f"[DRY RUN] Message {message_id} would be sent."

    def block_message(self, message_id: str, reason: str = "") -> bool:
        msg = self._pending.get(message_id)
        if msg:
            msg.approval_status = "BLOCKED"
            self._log_entry("blocked", msg)
            return True
        return False

    # ── Full bridge workflow ───────────────────────────────────────────────────

    def bridge(
        self,
        request: str,
        context: str = "",
        constraints: str = "",
        expected_output: str = "",
        dry_run: bool = True,
        auto_insert: bool = True,
    ) -> tuple[BridgeMessage, str]:
        """
        Full bridge workflow: draft → find window → insert (draft only by default).
        Returns (message, status_text).
        Never sends without approval.
        """
        msg = self.draft_message(
            request=request,
            context=context,
            constraints=constraints,
            expected_output=expected_output,
            dry_run=dry_run,
        )

        window_info = self.find_chatgpt_window()
        if not window_info:
            status = (
                "ChatGPT window not found. Make sure ChatGPT desktop app or browser tab "
                "is open and visible. Message drafted but not inserted."
            )
            return msg, status

        msg.target_window = window_info.get("title", "?")

        if auto_insert:
            success, detail = self.insert_message(msg, window_info, dry_run=dry_run)
            status = (
                f"Message drafted and {'placed (dry run)' if dry_run else 'inserted'}. {detail}\n"
                f"To send: call approve_send('{msg.id}') after Noah approves, "
                f"or type APPROVE_SEND_CHATGPT {msg.id}"
            )
        else:
            status = f"Message drafted (ID: {msg.id}). Call insert_message() to place it."

        return msg, status

    # ── Persistence ───────────────────────────────────────────────────────────

    def _log_entry(self, action: str, msg: BridgeMessage):
        self._log.append({
            "action": action,
            "message_id": msg.id,
            "at": datetime.now(timezone.utc).isoformat(),
            "target": msg.target_window,
            "status": msg.approval_status,
            "request_preview": msg.request[:80],
        })
        self._log = self._log[-MAX_LOG_ENTRIES:]

    def save_log(self):
        BRIDGE_LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
        BRIDGE_LOG_FILE.write_text(
            json.dumps(self._log, indent=2, default=str), encoding="utf-8"
        )

    def load_log(self):
        if BRIDGE_LOG_FILE.exists():
            try:
                self._log = json.loads(BRIDGE_LOG_FILE.read_text(encoding="utf-8"))
            except Exception:
                self._log = []

    def status(self) -> str:
        window = self.find_chatgpt_window()
        lines = [
            "",
            "  [CHATGPT BRIDGE STATUS]",
            f"  ChatGPT window found : {'YES — ' + window['title'] if window else 'NO'}",
            f"  Pending messages     : {len(self._pending)}",
            f"  Log entries          : {len(self._log)}",
            "",
        ]
        if self._pending:
            lines.append("  Pending drafts:")
            for mid, m in list(self._pending.items())[-5:]:
                lines.append(f"    [{mid}] {m.approval_status} — {m.request[:60]}")
        lines.append("")
        return "\n".join(lines)


# ── Module-level singleton ─────────────────────────────────────────────────────

_bridge: Optional[ChatGPTBridge] = None


def get_bridge() -> ChatGPTBridge:
    global _bridge
    if _bridge is None:
        _bridge = ChatGPTBridge()
    return _bridge


# ── Smoke test ────────────────────────────────────────────────────────────────

def _smoke_test() -> bool:
    print("=" * 60)
    print("chatgpt_bridge.py — Smoke Test (dry run, no desktop actions)")
    print("=" * 60)

    passed = 0
    failed = 0

    def check(label: str, condition: bool, detail: str = ""):
        nonlocal passed, failed
        ok = condition
        print(f"  [{'PASS' if ok else 'FAIL'}] {label}")
        if not ok and detail:
            print(f"         {detail}")
        if ok:
            passed += 1
        else:
            failed += 1

    bridge = ChatGPTBridge()

    # 1. Draft message creates envelope
    msg = bridge.draft_message(
        request="What is the best architecture for a governed AI continuity engine?",
        context="ORACLE.AI is a locally-run governed AI assistant for Noah Hawkes.",
        expected_output="A ranked list of architecture patterns with trade-offs.",
        dry_run=True,
    )
    check("draft_message creates BridgeMessage", msg is not None)
    check("Message ID is set", bool(msg.id))
    check("Status is DRAFT", msg.approval_status == "DRAFT")
    envelope = msg.envelope()
    check("Envelope contains ORACLE header", "ORACLE" in envelope)
    check("Envelope contains Request section", "Request:" in envelope)
    check("Envelope contains Approval status", "Approval status" in envelope)

    # 2. Secret redaction
    text_with_secrets = "My API key is sk-ant-api03-abc123xyz and password: s3cr3t!"
    cleaned, n = ChatGPTBridge.redact_secrets(text_with_secrets)
    check("API key is redacted", "sk-ant-api03" not in cleaned, f"got: {cleaned[:60]}")
    check("Password is redacted", "s3cr3t" not in cleaned, f"got: {cleaned[:80]}")
    check("Redaction count > 0", n > 0, f"got n={n}")

    msg_secret = bridge.draft_message(
        request="My API key is sk-ant-XXXX-test and password: testpass123",
        dry_run=True,
    )
    check("Secrets in request are redacted in draft",
          "sk-ant-XXXX" not in msg_secret.request, f"got: {msg_secret.request[:80]}")
    check("Redactions_applied recorded", msg_secret.redactions_applied > 0)

    # 3. Send is blocked without approval
    ok_send, detail_send = bridge.approve_send("nonexistent_id")
    check("approve_send fails for unknown ID", not ok_send)
    check("approve_send returns error message", bool(detail_send))

    # 4. Draft message is in pending
    check("Draft stored in pending", msg.id in bridge._pending)

    # 5. Block message
    bridge.block_message(msg.id, reason="test_block")
    ok_blocked, _ = bridge.approve_send(msg.id)
    check("Blocked message cannot be sent", not ok_blocked)

    # 6. find_chatgpt_window returns None cleanly when no ChatGPT open
    # (in smoke test environment there is no ChatGPT window — must not crash)
    result = bridge.find_chatgpt_window()
    check("find_chatgpt_window returns None when not found (no crash)",
          result is None or isinstance(result, dict))

    # 7. bridge() workflow with no window fails cleanly
    msg2 = bridge.draft_message(
        request="Test question for ChatGPT",
        dry_run=True,
    )
    # Manually simulate no-window path
    window_found = bridge.find_chatgpt_window()
    if window_found is None:
        check("bridge() fails cleanly without ChatGPT window", True)
    else:
        # If ChatGPT is actually open, dry-run insert
        success, detail = bridge.insert_message(msg2, window_found, dry_run=True)
        check("bridge() dry-run insert succeeds when window found", success)

    # 8. Compress context
    long_context = "x" * 10000
    compressed = ChatGPTBridge.compress_context(long_context)
    check("compress_context trims long text", len(compressed) < len(long_context))
    check("Compressed text notes truncation", "compressed" in compressed.lower())

    # 9. Status report builds without crash
    try:
        s = bridge.status()
        check("status() builds without crash", True)
        check("Status mentions ChatGPT window", "ChatGPT" in s)
    except Exception as e:
        check("status() builds without crash", False, str(e))
        check("Status mentions ChatGPT window", False)

    # 10. Log persistence
    bridge.save_log()
    check("Bridge log file written", BRIDGE_LOG_FILE.exists())
    bridge2 = ChatGPTBridge()
    check("Bridge log loads from disk", len(bridge2._log) >= 0)  # may be 0 if no sends

    print(f"\n{passed}/{passed + failed} smoke tests passed.")
    if failed:
        print(f"FAILED: {failed} test(s).")
    else:
        print("All smoke tests passed.")
    return failed == 0


# ── CLI ────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    args = sys.argv[1:]

    if "--smoke" in args or "smoke" in args:
        ok = _smoke_test()
        sys.exit(0 if ok else 1)

    bridge = get_bridge()

    if "--status" in args:
        print(bridge.status())
        sys.exit(0)

    if "--dry-run" in args:
        msg_idx = args.index("--message") if "--message" in args else -1
        request = args[msg_idx + 1] if msg_idx >= 0 and msg_idx + 1 < len(args) else "Test bridge message"
        msg, status = bridge.bridge(request=request, dry_run=True)
        print(msg.summary())
        print(f"\nStatus: {status}\n")
        sys.exit(0)

    print("Usage:")
    print("  python core/chatgpt_bridge.py --smoke")
    print("  python core/chatgpt_bridge.py --status")
    print("  python core/chatgpt_bridge.py --dry-run --message \"your question\"")
